name: Exercices de style
# markdown: redcarpet
# redcarpet:
#     extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables"]
markdown: kramdown
kramdown:
        input: GFM
        syntax_highlighter: rouge
paginate: 10 # pagination basted on number of posts
exclude: ["jekyll-serve.bat" ] # files to exclude
gems: [jekyll-paginate]


